global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: 'prometheus' 
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'kong'
    metrics_path: /metrics
    honor_labels: true
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets: ['kong:8001']

# Update the targets based on your setup
  # ensure the targets' host and port match the locations where Prometheus and Kong's Admin API are running

# You can validate the modified prometheus.yml file using promtool or a similar tool to ensure its correctness and restart Prometheus with the updated configuration
