global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: 'prometheus' 
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'kong'
    metrics_path: /metrics
    honor_labels: true
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets: ['kong:8001']
